### ISSUE TITLE
icone (genre maison) pour le base path ?

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/mediawiki-BreadcrumbList#1]

**Comment by Rudloff** [comment]
Je sais pas dessiner :/

**Comment by vbonhomme** [comment]
haha !

glyphicon-home in http://getbootstrap.com/components/#glyphicons ;)

2015-02-17 14:24 GMT+01:00 Pierre Rudloff notifications@github.com:

> Je sais pas dessiner :/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ShakePeers/mediawiki-BreadcrumbList/issues/1#issuecomment-74666670
> .

## 

vincentbonhomme.fr http://www.vincentbonhomme.fr

**Comment by Rudloff** [comment]
Ah oui pas con !

**Comment by vbonhomme** [comment]
magnifique <3

2015-02-17 15:14 GMT+01:00 Pierre Rudloff notifications@github.com:

> Closed #1
> https://github.com/ShakePeers/mediawiki-BreadcrumbList/issues/1 via
> e86c66b
> https://github.com/ShakePeers/mediawiki-BreadcrumbList/commit/e86c66b587706c0381c1871592e25589babe482b
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ShakePeers/mediawiki-BreadcrumbList/issues/1#event-236944663
> .

## 

vincentbonhomme.fr http://www.vincentbonhomme.fr

**Comment by vbonhomme** [comment]
mes tyentatives de cosmétique / Todo-isation :
https://shakepeers.org/Mod%C3%A8le:Vide

2015-02-17 15:16 GMT+01:00 Vincent Bonhomme bonhomme.vincent@gmail.com:

> magnifique <3
> 
> 2015-02-17 15:14 GMT+01:00 Pierre Rudloff notifications@github.com:
> 
> > Closed #1
> > https://github.com/ShakePeers/mediawiki-BreadcrumbList/issues/1 via
> > e86c66b
> > https://github.com/ShakePeers/mediawiki-BreadcrumbList/commit/e86c66b587706c0381c1871592e25589babe482b
> > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ShakePeers/mediawiki-BreadcrumbList/issues/1#event-236944663
> > .
> 
> ## 
> 
> vincentbonhomme.fr http://www.vincentbonhomme.fr

## 

vincentbonhomme.fr http://www.vincentbonhomme.fr
